import { Child, Booking, ChatMessage } from './types';

export const initialChildren: Child[] = [
  {
    id: 'emma',
    name: 'Emma Johnson',
    initials: 'EJ',
    yearGroup: 'Year 4',
    school: "St Michael's Primary",
    avatarBg: 'bg-primary',
    avatarText: 'text-on-primary',
    ringColor: 'ring-primary-fixed/40',
    tags: ['Mathematics', 'Reading', 'Spelling'],
    mathProgress: 88,
    englishProgress: 92,
  },
  {
    id: 'oliver',
    name: 'Oliver Williams',
    initials: 'OW',
    yearGroup: 'Year 6',
    school: 'Oakridge Grammar',
    avatarBg: 'bg-secondary',
    avatarText: 'text-on-secondary',
    ringColor: 'ring-secondary-fixed/50',
    tags: ['Fractions & Decimals', 'Algebra Basics', 'Creative Writing'],
    mathProgress: 74,
    englishProgress: 81,
  },
  {
    id: 'sophie',
    name: 'Sophie Baker',
    initials: 'SB',
    yearGroup: 'Year 2',
    school: 'Sunnybank Infants',
    avatarBg: 'bg-tertiary-container',
    avatarText: 'text-on-tertiary-container',
    ringColor: 'ring-tertiary-fixed/60',
    tags: ['Early Numeracy', 'Phonics'],
    mathProgress: 95,
    englishProgress: 90,
  },
];

export const initialBookings: Booking[] = [
  {
    id: 'b1',
    day: 'MON',
    date: '14',
    month: 'OCT',
    subject: 'MATHEMATICS',
    subjectType: 'math',
    title: 'Fractions foundations',
    status: 'Confirmed',
    time: '3:30 PM – 4:30 PM',
    tutor: 'Jessica Taylor',
    studio: 'Studio 1',
    note: 'Materials supplied by studio',
  },
  {
    id: 'b2',
    day: 'WED',
    date: '16',
    month: 'OCT',
    subject: 'ENGLISH & WRITING',
    subjectType: 'english',
    title: 'Storycraft & Sentence Structure',
    status: 'Confirmed',
    time: '4:00 PM – 5:00 PM',
    tutor: 'Marcus Vance',
    studio: 'Studio 3',
    note: 'Includes creative writing journal',
  },
  {
    id: 'b3',
    day: 'SAT',
    date: '19',
    month: 'OCT',
    subject: 'MATHEMATICS',
    subjectType: 'math',
    title: 'Multiplication Mastery & Decimals',
    status: 'Confirmed',
    time: '10:00 AM – 11:00 AM',
    tutor: 'Jessica Taylor',
    studio: 'Studio 1',
    note: 'Weekly fraction quiz review',
  },
];

export const initialMessages: ChatMessage[] = [
  {
    id: 'm1',
    sender: 'tutor',
    text: "Hello Sarah! Emma's session tomorrow will focus on fractions foundations. Please bring her workbook.",
    timestamp: '9:15 AM',
  },
  {
    id: 'm2',
    sender: 'parent',
    text: 'Thanks Jessica! Emma is excited. Will do.',
    timestamp: '9:22 AM',
    status: 'read',
  },
  {
    id: 'm3',
    sender: 'tutor',
    text: 'Great! See you both at Studio 1.',
    timestamp: 'Just now',
  },
];
